# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'https-lenpaul-github-io-lagrange'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ' '

menu:
- {name: 'About',   url: 'about.html'}
- {name: 'Publications & Presentations', url: 'publications.html'}
#- {name: 'Writing', url: 'writing.html'}
#- {name: 'Gallery', url: 'gallery.html'}
- {name: 'CV', url: 'cv.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github',     link: 'https://github.com/hongbinqing'}
# - {icon: 'instagram',  link: 'https://www.instagram.com/zhengwu_ma/'}
- {icon: 'twitter',    link: 'https://twitter.com/HongbinQing'}
- {icon: 'linkedin',   link: 'https://www.linkedin.com/in/hongbinqing/'}
- {icon: 'envelope',   link: 'mailto:hqing2-c@my.cityu.edu.hk'}

# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text

sharing_button_prompt: 'Feel free to share!'

related_posts: 'You may also enjoy:'

post_date_prefix: 'Written on'
